# SPDX-License-Identifier: Apache-2.0
# Copyright 2023 Canonical Ltd.
# Copyright 2024 Intel Corporation.

name: abot_automation

on:
  workflow_dispatch:
jobs:
    
  
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://10.176.27.188:8080/"
        user: "admin"
        token: ${{ secrets.JENKINS_PAT }}
        job: "ABot-SDCORE-CI-Pipeline"
